spring:
    profiles.active: dev	
---
spring:
    profiles: dev
    #如果不使用JMS，那么设为false,否则报.MXBean already registered with name org.apache.commons.pool2
    jmx.enabled: false 
server:
    port: 10110
---
spring:
    profiles: prod
server:
    port: 10110			